---
title: "Introduction for Developers of Population Genetic R Packages"
author: "Zhian N. Kamvar"
date: "March 19, 2015"
output: html_document
---

Introduction
=======

You are reading this introduction because you are interested in contributing an
R package to the population genetics community. You might have some R scripts
lying around that implement a specific calculation, or possibly implements a new
method of data visualization. In either case, it is important to understand what
methods currently exist in population genetics and how you can utilize common 
classes to ensure interoperability between different packages. 

The goal of these series of tutorials is to introduce you to:

 - The current ecology of packages in R
    - Types of analyses that they each perform
    - Types of genetic data that can be handled by each
    - Classes implemented
    - Functions for conversion

Resources
=======

Below are some resources that can get you started writing R packages. We will 
have examples utilizing existing packages in these tutorials.

 - [Hadley Wickham's Guide For Creating R Packages](http://r-pkgs.had.co.nz/)
 - [S4 Classes in detail](http://adv-r.had.co.nz/S4.html)
 - [S3 Classes in detail](http://adv-r.had.co.nz/S3.html)
 - [A not so short introduction to S4](http://cran.r-project.org/doc/contrib/Genolini-S4tutorialV0-5en.pdf)

Conclusions
=======

R is an open source language with a strong community of developers contributing
new methods and analyses. The population genetics community has worked hard to 
create data classes that can be used efficiently between packages, expanding the
number of analyses that can be done by users in a reproducible manner. This 
interoperability also means that it is more likely for your method to be utilized
as the users would not have to manually change file formats, lowering the 
barrier to integrate your method into their workflow.
